name: shoplist
description: "A manager for your shopping lists."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Datenbanken
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  provider: ^6.1.2

  # UI & Icons
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  characters: ^1.4.0

  # Firebase (kompatible Versionen!)
  firebase_core: ^3.10.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.0
  flutter_riverpod: ^3.0.3
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  analyzer: ^6.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Neutral.png
