name: shoplist
description: "A manager for your shopping lists."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  provider: ^6.0.0

  # UI & Icons
  lucide_icons: ^0.257.0

  # Device Preview fÃ¼r responsives Testing
  device_preview: ^1.3.1

  characters: ^1.4.0
  material_color_utilities: ^0.11.1

  google_fonts: ^6.0.0

  # Firebase
  firebase_core: ^4.2.1 
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.0

  flutter_lints: ^6.0.0

  # App-Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Title.png
    - assets/Neutral.png
    - assets/icon.png
